spring:
  application:
    name: Trouve Ton Match
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: user
      password: 1234
logging:
  level:
    org.springframework.security:
      DEBUG

